export const en = {
  translation: {
    backToHome: "Back to Home",
    translationManagementTitle: "Translation Management",
    translationManagementDescription: "Manage translations for all supported languages.",
    translationKeysTitle: "Translation Keys",
    translationKeysDescription: "View and edit translations for each key.",
    addNewKey: "Add New Key",
    addNewKeyTitle: "Add a New Translation Key",
    newKeyPlaceholder: "Enter new key (e.g. 'myNewKey')",
    addKeyButton: "Add Key",
    selectLanguage: "Select language to edit:",
    selectLanguagePlaceholder: "Select a language",
    translationKey: "Key",
    translationValue: "Translation",
    enterTranslation: "Enter translation...",
    saveChangesButton: "Save Changes",
    saveSuccess: "Translations for {{lang}} saved successfully.",
    saveError: "Failed to save translations for {{lang}}.",
    translationLoadError: "Failed to load translations.",
    invalidKeyError: "Invalid key. Use only alphanumeric characters and underscores.",
    duplicateKeyError: "Key already exists.",
    keyAddedSuccess: "New key added successfully.",
  },
};
